version: 0.2

env:
  parameter-store:
    REACT_APP_API_URL: /campusarena/REACT_APP_API_URL

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd client && npm ci && cd ..

  build:
    commands:
      - cd client && npm run build && cd ..
      - zip -r backend-deployment.zip server/ appspec.yml scripts/

  post_build:
    commands:
      - aws s3 sync client/build/ s3://$FRONTEND_BUCKET --delete
      - aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"
      - aws s3 cp backend-deployment.zip s3://$FRONTEND_BUCKET/deployments/backend-deployment.zip
      - |
        aws deploy create-deployment
          --application-name production-CampusArena
          --deployment-group-name production-CampusArena-DG
          --s3-location bucket=$FRONTEND_BUCKET,key=deployments/backend-deployment.zip,bundleType=zip
          --region ap-south-1

artifacts:
  files:
    - "**/*"
  base-directory: client/build
